export const SIGN_IN_NAVIGATION = "SIGN_IN_NAVIGATION";
export const SIGN_UP_NAVIGATION = "SIGN_UP_NAVIGATION";
export const TODO_GROUP_NAVIGATION = "TODO_GROUP_NAVIGATION";
export const TODO_NAVIGATION = "TODO_NAVIGATION";
export const ADD_TODO_NAVIGATION = "ADD_TODO_NAVIGATION";
export const EDIT_TODO_NAVIGATION = "EDIT_TODO_NAVIGATION";

export const AUTH_VIEW = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
};

export const APP_VIEW = {
  HOME: "HOME",
  AUTH: "AUTH",
  TODO: "TODO",
};
